### ISSUE TITLE
yaml error after switching to conda environment analysis from NCAR-pangeo-tutorial

### ISSUE THREAD

**Issue by klindsay28** [matt-long/data-catalog#2]
I've switched to using the conda environment `analysis` from NCAR-pangeo-tutorial and am now getting the following error when I try to use build_catalog:
```
Traceback (most recent call last):
  File "./build_catalog.py", line 5, in <module>
    data_catalog.build_catalog('expr_metadata.yaml', clobber=True)
  File "/gpfs/fs1/work/klindsay/analysis/CESM2_coup_carb_cycle_JAMES/data_catalog.py", line 87, in build_catalog
    catalog_definition = yaml.safe_load(f)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "./lib_data_catalog/cesm_definitions.yml", line 22, column 7
```

The full path of `./lib_data_catalog/cesm_definitions.yml` is `/glade/work/klindsay/analysis/CESM2_coup_carb_cycle_JAMES/lib_data_catalog/cesm_definitions.yml`. The offending lines appear to be
```
replacements:
  freq:
    - !!python/tuple [monthly, month_1]
    - !!python/tuple [daily, day_1]
    - !!python/tuple [yearly, year_1]
```

The version of yaml in the conda environment is 0.1.7.

Any suggestions on how to work around this error?

**Comment by klindsay28** [comment]
Fixed...

The problem is that I had switched `yaml.load` to `yaml.safe_load` to avoid `YAMLLoadWarning` messages, and `yaml.safe_load` does not handle these python-specific tags. If I instead switch to `yaml.full_load`, then it looks like it's working, and I also don't get the `YAMLLoadWarning` messages.
